language: julia

os:
  - linux
  - osx
  - windows
  - freebsd

julia:
  - 1.0
  - 1
  - nightly

matrix:
  allow_failures:
    - julia: nightly

sudo: required

git:
  depth: 9999

notifications:
  email: false

branches:
  only:
    - master

after_success:
  - julia -e 'if Sys.islinux() && string(VERSION)[1:3] == "1.4"
      using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())
    end'

